-- CreateTable
CREATE TABLE `money_flow` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `ts_code` VARCHAR(20) NOT NULL,
    `trade_date` DATE NOT NULL,
    `buy_sm_vol` INTEGER NULL,
    `buy_sm_amount` DOUBLE NULL,
    `sell_sm_vol` INTEGER NULL,
    `sell_sm_amount` DOUBLE NULL,
    `buy_md_vol` INTEGER NULL,
    `buy_md_amount` DOUBLE NULL,
    `sell_md_vol` INTEGER NULL,
    `sell_md_amount` DOUBLE NULL,
    `buy_lg_vol` INTEGER NULL,
    `buy_lg_amount` DOUBLE NULL,
    `sell_lg_vol` INTEGER NULL,
    `sell_lg_amount` DOUBLE NULL,
    `buy_elg_vol` INTEGER NULL,
    `buy_elg_amount` DOUBLE NULL,
    `sell_elg_vol` INTEGER NULL,
    `sell_elg_amount` DOUBLE NULL,
    `net_mf_vol` INTEGER NULL,
    `net_mf_amount` DOUBLE NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `idx_trade_date` (`trade_date`),
    INDEX `idx_ts_code` (`ts_code`),
    UNIQUE INDEX `unique_stock_date` (`ts_code`, `trade_date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;